### ISSUE TITLE
PF-1233: no check runs against the merged commit, so a semantic conflict red-lines main and every unrelated PR

### ISSUE THREAD

**Issue by Tristan578** [Tristan578/project-forge#9495]
## Correction to the original framing

The original title and root-cause section of this issue were **wrong**, and I am rewriting rather than editing around it.

I claimed "no CI job compiles the engine's native test target." That is false. `quality-gates.yml:295` runs:

```yaml
      - name: Run engine tests
        run: cargo test --lib --features bevy/x11
```

inside the `WASM Build` job. The gate exists and works — it is currently red on every open PR that trips its `if:` condition, which is how I re-found this.

## The actual problem

`quality-gates.yml:259` gates the whole `WASM Build` job on:

```yaml
    if: inputs.engine-changed || inputs.ci-changed
```

That is correct as a cost control, and it did fire on the PR that introduced the break. The gap is **what happens between a PR going green and that PR landing**.

`#9466` widened `snapshot_scene`'s `tilemap_skeleton2d_query` parameter from a 7-element to a 10-element tuple (adding `TerrainData`, `TerrainMeshData`, `AnimationClipData`) and updated every production call site. The `scene_round_trip_tests` harness inside `engine_mode.rs` still passes the 7-element tuple. Result on `main` at `e21dfea3`:

```
error[E0308]: mismatched types
   --> src/core/engine_mode.rs:546:13
    |
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^ expected a tuple with 10 elements, found one with 7 elements
```

This is a **semantic merge conflict**: each contributing PR was green against the `main` it was tested on, and the combination is red. Nothing re-ran the engine gate against the merged result, so `main` went red and stayed red.

The repository has no merge queue and `CI Success` is a `pull_request`-only workflow, so **no check ever evaluates the post-merge commit**. Any pair of independently-green PRs that disagree semantically lands broken, and the next PR to touch `engine/**` or `.github/**` inherits a red `WASM Build` it did not cause.

## Blast radius, observed

The compile error is repaired in #9487. Until that merges, these four PRs are red purely by inheritance — every one of them is CI-only and touches no Rust:

- #9477, #9478, #9486 (`ci-changed` → job runs → inherits the break)
- #9489 (same)

That is the cost of the gap: four clean PRs unmergeable on a failure none of them introduced, and no signal distinguishing them from a genuine regression.

## Acceptance criteria

- [ ] Enable a **GitHub merge queue** on `main` so the engine gate (and the rest of `CI Success`) runs against the actual merged commit, not the PR head. This is the fix that addresses the class, not the instance.
- [ ] Alternatively/additionally: run `quality-gates.yml` on `push: main` so a red `main` is detected immediately and attributed to the merge that caused it, rather than surfacing on an unrelated contributor's PR hours later.
- [ ] Document in `.claude/rules/gotchas-build-ci.md` that a red `WASM Build` on a PR with no Rust changes means `main` is broken — check `main` before debugging the PR.

## Not in scope

Repairing the current `engine_mode.rs` break — that ships in #9487, which restores `cargo test --lib` to 887 passed / 0 failed.
